//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeCourseReviewDetailSpam
    {
        public int CollegeCourseReviewDetailSpamId { get; set; }
        public int CollegeCourseReviewDetailId { get; set; }
        public int UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsReviewed { get; set; }
    }
}
