//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeFacility
    {
        public int CollegeFacilityId { get; set; }
        public int FacilityId { get; set; }
        public int CollegeId { get; set; }
        public bool IsAvailable { get; set; }
    }
}
