//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeCourseReviewDetail
    {
        public int CollegeCourseReviewDetailId { get; set; }
        public int CollegeCourseReviewId { get; set; }
        public int ReviewCategoryId { get; set; }
        public string ReviewTitle { get; set; }
        public string GreatDesc { get; set; }
        public string NotGreatDesc { get; set; }
        public string WhyDesc { get; set; }
        public int Rating { get; set; }
        public bool IsActive { get; set; }
        public string Action { get; set; }
    }
}
