//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeFamousAlumni
    {
        public int CollegeFamousAlumniId { get; set; }
        public int CollegeId { get; set; }
        public string AlumniName { get; set; }
        public string AlumniDesc { get; set; }
        public string AlumniPhoto { get; set; }
        public string AlumniLink { get; set; }
    }
}
