//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        public int CollegeId { get; set; }
        public string CollegeName { get; set; }
        public string CollegeLogo { get; set; }
        public string CollegeDesc { get; set; }
        public string EstablishedYear { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public int CountryId { get; set; }
        public string PinCode { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Phone { get; set; }
        public string EmailAddress { get; set; }
        public string TransportDetail { get; set; }
        public string NotifEmailToCollege { get; set; }
        public bool SportsAvailable { get; set; }
        public string WebSiteURL { get; set; }
        public string Accreditation { get; set; }
        public Nullable<int> NoOfStudents { get; set; }
        public int CollegeTypeId { get; set; }
        public int StudentTypeId { get; set; }
        public Nullable<int> AffiliatedToId { get; set; }
        public bool IsAccomodation { get; set; }
        public Nullable<int> AccomodationTypeId { get; set; }
        public string Activities { get; set; }
        public string ProspectusLink { get; set; }
        public Nullable<int> AcademicSessionId { get; set; }
        public string CampusInfrastructure { get; set; }
        public Nullable<int> SubmittedById { get; set; }
        public long ViewCount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
