//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeCourse
    {
        public int CollegeCourseId { get; set; }
        public int CollegeId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public int TimingId { get; set; }
        public string Duration { get; set; }
        public Nullable<int> TotalFee { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public string EligibilityDesc { get; set; }
        public string Accreditation { get; set; }
        public bool IsPlacementDone { get; set; }
    }
}
