//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeCoursePlacement
    {
        public int CollegeCoursePlacementId { get; set; }
        public int CollegeCourseId { get; set; }
        public Nullable<int> NumberOfStudentsPlaced { get; set; }
        public Nullable<decimal> PercentOfStudentsPlaced { get; set; }
        public string PlacementDesc { get; set; }
        public string CompanyList { get; set; }
        public Nullable<decimal> HighestPackage { get; set; }
        public Nullable<decimal> AvgSalaryReceived { get; set; }
    }
}
