//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeCourseTimeLine
    {
        public int CollegeCourseTimeLineId { get; set; }
        public int CollegeCourseId { get; set; }
        public Nullable<System.DateTime> EntranceDate { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string Campus { get; set; }
        public string Scholarship { get; set; }
    }
}
