//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeCourseApplProcess
    {
        public int CollegeCourseApplProcessId { get; set; }
        public int CollegeCourseId { get; set; }
        public string ExtranceExams { get; set; }
        public string Description { get; set; }
        public string Syllabus { get; set; }
    }
}
