//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expert
    {
        public int ExpertId { get; set; }
        public string ExpertName { get; set; }
        public string ExpertPhoto { get; set; }
        public string ExpertDesc { get; set; }
    }
}
