//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertReview
    {
        public int ExpertReviewId { get; set; }
        public int ExpertId { get; set; }
        public int CollegeCourseId { get; set; }
        public string ReviewTitle { get; set; }
        public string ReviewInDetail { get; set; }
        public int Rating { get; set; }
    }
}
