//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string HomeTown { get; set; }
        public string ZipCode { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string MobileNo { get; set; }
        public string AboutUser { get; set; }
        public string UserPhoto { get; set; }
        public string LanguagesSpoken { get; set; }
        public Nullable<bool> IsUserVerified { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public string FieldOfInterest { get; set; }
        public int UserLoginID { get; set; }
    }
}
