//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.UserProfile.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int UserLoginID { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsFacebookLogin { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FBUserID { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public string VerificationCode { get; set; }
    }
}
