//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ClientResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLLEGE....
        /// </summary>
        internal static string CollegePlaceholderText {
            get {
                return ResourceManager.GetString("CollegePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply College..
        /// </summary>
        internal static string CollegeRequiredMessage {
            get {
                return ResourceManager.GetString("CollegeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply Confirm Password..
        /// </summary>
        internal static string ConfirmPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COURSE....
        /// </summary>
        internal static string CoursePlaceholderText {
            get {
                return ResourceManager.GetString("CoursePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply Course..
        /// </summary>
        internal static string CourseRequiredMessage {
            get {
                return ResourceManager.GetString("CourseRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEGREE TYPE....
        /// </summary>
        internal static string DegreeTypePlaceholderText {
            get {
                return ResourceManager.GetString("DegreeTypePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply Degree Type..
        /// </summary>
        internal static string DegreeTypeRequiredMessage {
            get {
                return ResourceManager.GetString("DegreeTypeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply Email Address..
        /// </summary>
        internal static string EmailAddressRequiredMessage {
            get {
                return ResourceManager.GetString("EmailAddressRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occcured while logging in with Facebook Account.
        /// </summary>
        internal static string FacebookLoginErrorMessage {
            get {
                return ResourceManager.GetString("FacebookLoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply First Name..
        /// </summary>
        internal static string FirstNameRequiredMessage {
            get {
                return ResourceManager.GetString("FirstNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        internal static string InstitutePassingYearPlaceholderText {
            get {
                return ResourceManager.GetString("InstitutePassingYearPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Valid Email Address..
        /// </summary>
        internal static string InValidEmailAddressMessage {
            get {
                return ResourceManager.GetString("InValidEmailAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Phone Number..
        /// </summary>
        internal static string InvalidPhoneNumberMessage {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Zip Code..
        /// </summary>
        internal static string InvalidZipCodeMessage {
            get {
                return ResourceManager.GetString("InvalidZipCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 6 and 128 characters long and contain three of the following 4 items: upper case letter, lower case letter, a symbol, a number.
        /// </summary>
        internal static string PasswordComplexityNotMetMessage {
            get {
                return ResourceManager.GetString("PasswordComplexityNotMetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match..
        /// </summary>
        internal static string PasswordMustMatchMessage {
            get {
                return ResourceManager.GetString("PasswordMustMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply Password..
        /// </summary>
        internal static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHOOL.
        /// </summary>
        internal static string SchoolNamePlaceholderText {
            get {
                return ResourceManager.GetString("SchoolNamePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply SchoolName..
        /// </summary>
        internal static string SchoolNameRequiredMessage {
            get {
                return ResourceManager.GetString("SchoolNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAJOR....
        /// </summary>
        internal static string SubjectPlaceholderText {
            get {
                return ResourceManager.GetString("SubjectPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply Major..
        /// </summary>
        internal static string SubjectRequiredMessage {
            get {
                return ResourceManager.GetString("SubjectRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply Year..
        /// </summary>
        internal static string YearRequiredMessage {
            get {
                return ResourceManager.GetString("YearRequiredMessage", resourceCulture);
            }
        }
    }
}
