//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LabelResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT YOU:.
        /// </summary>
        internal static string AboutUserLabel {
            get {
                return ResourceManager.GetString("AboutUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Another.
        /// </summary>
        internal static string AddAnotherInstituteButtonText {
            get {
                return ResourceManager.GetString("AddAnotherInstituteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF BIRTH:.
        /// </summary>
        internal static string BirthDateLabel {
            get {
                return ResourceManager.GetString("BirthDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT COLLEGE.
        /// </summary>
        internal static string CollegeDescText {
            get {
                return ResourceManager.GetString("CollegeDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLLEGE.
        /// </summary>
        internal static string CollegeNameText {
            get {
                return ResourceManager.GetString("CollegeNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLLEGES.
        /// </summary>
        internal static string CollegeSelectionPageTitleText {
            get {
                return ResourceManager.GetString("CollegeSelectionPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE-TYPE PASSWORD.
        /// </summary>
        internal static string ConfirmPasswordPlaceholderText {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER EMAIL.
        /// </summary>
        internal static string EmailPlaceholderText {
            get {
                return ResourceManager.GetString("EmailPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL VERIFICATION.
        /// </summary>
        internal static string EmailVerificationPageTitle {
            get {
                return ResourceManager.GetString("EmailVerificationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing User?.
        /// </summary>
        internal static string ExistingUserQuestionText {
            get {
                return ResourceManager.GetString("ExistingUserQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login With Facebook.
        /// </summary>
        internal static string FacebookLoginButtonText {
            get {
                return ResourceManager.GetString("FacebookLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST NAME:.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENDER:.
        /// </summary>
        internal static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME TOWN:.
        /// </summary>
        internal static string HomeTownLabel {
            get {
                return ResourceManager.GetString("HomeTownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT/PAST ACADEMIC INST..
        /// </summary>
        internal static string InstituteSectionTitleText {
            get {
                return ResourceManager.GetString("InstituteSectionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGES SPOKEN:.
        /// </summary>
        internal static string LanguagesSpokenLabel {
            get {
                return ResourceManager.GetString("LanguagesSpokenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST NAME:.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDDLE NAME:.
        /// </summary>
        internal static string MiddleNameLabel {
            get {
                return ResourceManager.GetString("MiddleNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOBILE:.
        /// </summary>
        internal static string MobileNoLabel {
            get {
                return ResourceManager.GetString("MobileNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User?.
        /// </summary>
        internal static string NewUserQuestionText {
            get {
                return ResourceManager.GetString("NewUserQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string PagerNextButtonText {
            get {
                return ResourceManager.GetString("PagerNextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string PagerPrevButtonText {
            get {
                return ResourceManager.GetString("PagerPrevButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string PasswordPlaceolderText {
            get {
                return ResourceManager.GetString("PasswordPlaceolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Next.
        /// </summary>
        internal static string SaveUserProfileButtonText {
            get {
                return ResourceManager.GetString("SaveUserProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInPageTitleText {
            get {
                return ResourceManager.GetString("SignInPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIELD OF INTERESTS:.
        /// </summary>
        internal static string UserFieldOfInterestLabel {
            get {
                return ResourceManager.GetString("UserFieldOfInterestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTO:.
        /// </summary>
        internal static string UserPhotoLabel {
            get {
                return ResourceManager.GetString("UserPhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string UserProfilePageTitleText {
            get {
                return ResourceManager.GetString("UserProfilePageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFICATION CODE.
        /// </summary>
        internal static string VerificationCodePlaceholderText {
            get {
                return ResourceManager.GetString("VerificationCodePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string VerifyEmailButtonText {
            get {
                return ResourceManager.GetString("VerifyEmailButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP CODE:.
        /// </summary>
        internal static string ZipCodeLabel {
            get {
                return ResourceManager.GetString("ZipCodeLabel", resourceCulture);
            }
        }
    }
}
